---
     - name: installation or check that ftpd installed and latest
       yum:
         name: vsftpd
         state: latest
     
     - name: enable_service_ftpd_on_firewall
       firewalld:
         service: ftp
         state: enabled
         permanent: true
      
     - name: change_ftpd_config_via_j2template
       template:
         src: vsftpd.conf.j2
         dest: /etc/vsftpd/vsftpd.conf

     - name: service ftpd start
       service:
        name: vsftpd
        enabled: yes
        state: started
